#include "music.h"

#define SIXTEENTH_NOTE_MS           100U
#define EIGHTH_NOTE_MS              200U
#define QUARTER_NOTE_MS             400U
#define HALF_NOTE_MS                800U
#define THREEQ_NOTE_MS             1200U
#define LONG_NOTE_MS               1600U

/* 
 * Phrase definitions mainly control LEDs
 * Roughly one phrase per 8 notes
 * (excluding beginning)
 */
const note_t g_twinkle_song[] =
{
    {NOTE_D4_HZ, QUARTER_NOTE_MS,   0U},
    {NOTE_D4_HZ, QUARTER_NOTE_MS,   0U},
    {NOTE_D4_HZ, QUARTER_NOTE_MS,   0U},
    {NOTE_D4_HZ, QUARTER_NOTE_MS,   0U},

    {NOTE_E4_HZ, QUARTER_NOTE_MS,   1U},
    {NOTE_E4_HZ, QUARTER_NOTE_MS,   1U},
    {NOTE_E4_HZ, QUARTER_NOTE_MS,   1U},
    {NOTE_E4_HZ, QUARTER_NOTE_MS,   1U},

    {NOTE_C4_HZ, QUARTER_NOTE_MS,   3U},
    {NOTE_C4_HZ, QUARTER_NOTE_MS,   3U},
    {NOTE_C4_HZ, QUARTER_NOTE_MS,   3U},
    {NOTE_C4_HZ, QUARTER_NOTE_MS,   3U},

    {NOTE_C4_HZ, EIGHTH_NOTE_MS,    4U},
    {NOTE_C4_HZ, SIXTEENTH_NOTE_MS, 4U},
    {NOTE_C4_HZ, EIGHTH_NOTE_MS,    4U},
    {NOTE_C4_HZ, SIXTEENTH_NOTE_MS, 4U},
    {NOTE_C4_HZ, EIGHTH_NOTE_MS,    4U},
    {NOTE_C4_HZ, SIXTEENTH_NOTE_MS, 4U},
    {NOTE_C4_HZ, EIGHTH_NOTE_MS,    4U},
    {NOTE_C4_HZ, SIXTEENTH_NOTE_MS, 4U},

    {NOTE_G4_HZ, QUARTER_NOTE_MS,   5U},
    {NOTE_B4_HZ, QUARTER_NOTE_MS,   5U},
    {NOTE_D4_HZ, QUARTER_NOTE_MS,   5U},
    {NOTE_Fs_HZ, SIXTEENTH_NOTE_MS, 5U},
    {NOTE_G4_HZ, HALF_NOTE_MS,      5U},
    {NOTE_Fs_HZ, QUARTER_NOTE_MS,   5U},
    {NOTE_E4_HZ, QUARTER_NOTE_MS,   5U},
    {NOTE_D4_HZ, QUARTER_NOTE_MS,   5U},

    {NOTE_A4_HZ, QUARTER_NOTE_MS,   6U},
    {NOTE_G4_HZ, QUARTER_NOTE_MS,   6U},
    {NOTE_G4_HZ, QUARTER_NOTE_MS,   6U},
    {NOTE_Fs_HZ, QUARTER_NOTE_MS,   6U},
    {NOTE_G4_HZ, QUARTER_NOTE_MS,   6U},
    {NOTE_Fs_HZ, QUARTER_NOTE_MS,   6U},
    {NOTE_D4_HZ, HALF_NOTE_MS,      6U},

    {NOTE_D4_HZ, EIGHTH_NOTE_MS,    7U},
    {NOTE_C4_HZ, QUARTER_NOTE_MS,   7U},
    {NOTE_E4_HZ, QUARTER_NOTE_MS,   7U},
    {NOTE_G4_HZ, QUARTER_NOTE_MS,   7U},
    {NOTE_A4_HZ, EIGHTH_NOTE_MS,    7U},
    {NOTE_B4_HZ, HALF_NOTE_MS,      7U},
    {NOTE_A4_HZ, QUARTER_NOTE_MS,   7U},
    {NOTE_G4_HZ, QUARTER_NOTE_MS,   7U},
    {NOTE_E4_HZ, QUARTER_NOTE_MS,   7U},
    {NOTE_C4_HZ, QUARTER_NOTE_MS,   7U},

    {NOTE_Eb_HZ, SIXTEENTH_NOTE_MS, 8U},
    {NOTE_G4_HZ, HALF_NOTE_MS,      8U},
    {NOTE_A4_HZ, QUARTER_NOTE_MS,   8U},
    {NOTE_Bb_HZ, QUARTER_NOTE_MS,   8U},
    {NOTE_A4_HZ, QUARTER_NOTE_MS,   8U},
    {NOTE_F4_HZ, QUARTER_NOTE_MS,   8U},
    {NOTE_Eb_HZ, QUARTER_NOTE_MS,   8U},

    {NOTE_A4_HZ, QUARTER_NOTE_MS,   9U},
    {NOTE_G4_HZ, SIXTEENTH_NOTE_MS, 9U},
    {NOTE_G4_HZ, HALF_NOTE_MS,      9U},
    {NOTE_Fs_HZ, QUARTER_NOTE_MS,   9U},
    {NOTE_G4_HZ, QUARTER_NOTE_MS,   9U},
    {NOTE_Fs_HZ, QUARTER_NOTE_MS,   9U},
    {NOTE_E4_HZ, QUARTER_NOTE_MS,   9U},
    {NOTE_D4_HZ, QUARTER_NOTE_MS,   9U},

    {NOTE_G4_HZ, QUARTER_NOTE_MS,   10U},
    {NOTE_B4_HZ, SIXTEENTH_NOTE_MS, 10U},
    {NOTE_D4_HZ, HALF_NOTE_MS,      10U},
    {NOTE_Fs_HZ, QUARTER_NOTE_MS,   10U},
    {NOTE_G4_HZ, QUARTER_NOTE_MS,   10U},
    {NOTE_E4_HZ, QUARTER_NOTE_MS,   10U},
    {NOTE_D4_HZ, QUARTER_NOTE_MS,   10U},
    
    // slightly abridged 
    {NOTE_B4_HZ, QUARTER_NOTE_MS,   11U},
    {NOTE_A4_HZ, QUARTER_NOTE_MS,   11U},
    {NOTE_G4_HZ, QUARTER_NOTE_MS,   11U},
    {NOTE_E4_HZ, QUARTER_NOTE_MS,   11U},
    {NOTE_Eb_HZ, QUARTER_NOTE_MS,   11U},
    {NOTE_A4_HZ, THREEQ_NOTE_MS,    11U},
    {NOTE_B4_HZ, QUARTER_NOTE_MS,   11U},
    {NOTE_G4_HZ, LONG_NOTE_MS,      11U}
 

 
 };

const uint16_t g_ui16TwinkleNoteCount =
    (uint16_t)(sizeof(g_twinkle_song) / sizeof(g_twinkle_song[0]));
